title: EJ-pro 포트폴리오
description: Web & Security Engineer
site_title: '@EJ-pro 포트폴리오'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: EJ-pro
email: hsshss2522@naver.com

# absolute or relative
profile_picture: assets/images/profile.jpg

# Google Analytics ID
google_analytics: 